package com.demo.client;

import java.util.Calendar;

import org.hibernate.Session;
import org.hibernate.Transaction;

import com.demo.entity.AssignedStrategyEntity;
import com.demo.entity.IdentityStrategyEntity;
import com.demo.entity.IncrementStrategyEntity;
import com.demo.util.HibernateUtil;

public class ManagementSystemClient {
	
	public static void main(String[] args) {
		incrementStrategy();
		identityStrategy();
		assignedStrategy();
	}
	private static void incrementStrategy() {
		Session session = HibernateUtil.getSession();
		IncrementStrategyEntity incObj = new IncrementStrategyEntity();
		Transaction tx = session.beginTransaction();
		incObj.setDate(Calendar.getInstance());
		session.save(incObj);
		tx.commit();
		session.close();
	}

	private static void identityStrategy() {
		Session session = HibernateUtil.getSession();
		IdentityStrategyEntity idenObj = new IdentityStrategyEntity();
		Transaction tx = session.beginTransaction();
		idenObj.setDate(Calendar.getInstance());
		session.save(idenObj);
		tx.commit();
		session.close();
	}

	private static void assignedStrategy() {
		// id should be generated by the application
		Session session = HibernateUtil.getSession();
		AssignedStrategyEntity asObj = new AssignedStrategyEntity();
		Transaction tx = session.beginTransaction();
		asObj.setId(1);
		asObj.setDate(Calendar.getInstance());
		session.save(asObj);
		tx.commit();
		session.close();
	}
}
